name: Mac Clayton
description: Mac Clayton's personal blog
markdown: redcarpet
pygments: true
permalink: /:categories/:title
exclude: ["config.json", "Gemfile", "Gemfile.lock", "Rakefile", "README.md", "*.scss"]
